### ISSUE TITLE
Architecture for T-UE system

### ISSUE THREAD

**Issue by bjones1** [oran-testing/soft-t-ue#12]
Here's an issue to discuss the architecture for the T-UE setup. @cueltschey has a [nice diagram](https://github.com/oran-testing/soft-t-ue/blob/main/README.md) for his proposal. My thoughts:

1. Partition the design into one (or more) T-UE systems along with a single system that runs gNodeB, the open5G stacks., and anything else we need (scapy for pcap, iperf3, etc.)
2. For now, a single T-UE can run on the same system as the gNodeB/open5G software. It can use ZMQ as a fake channel for testing simplicity.
3. On startup, the server should auto-start gNodeB, open5G, etc. See #11.
4. The Python GUI should ideally borrow heavily from Grafana to allow us to easily present a lot of useful data with little effort on our part.

**Comment by cueltschey** [comment]
We now have a working gnb and UE controller pair that connect together and execute one attack (with more to come).
![2024-08-03T09:00:14,000452317-06:00](https://github.com/user-attachments/assets/d8282804-79d9-4357-b69e-36f1e16799bb)

**Comment by joshuamoorexyz** [comment]
Has this issue served it's purpose or is there more discussion necessary?

**Comment by bjones1** [comment]
Close it IHMO.
