### ISSUE TITLE
Explore Metrics that SRS already provides via Grafana 

### ISSUE THREAD

**Issue by joshuamoorexyz** [oran-testing/soft-t-ue#13]

**Comment by joshuamoorexyz** [comment]
Here is the way that they are capturing metrics from the RAN: https://github.com/kubernetes-sigs/metrics-server

**Comment by joshuamoorexyz** [comment]
Prateek provided the existing metrics on teams. I am posting here.

The current available metrics in grafana GUI is below
DL Bitrate
UL Bitrate
UL SNR
DL MCS
UL MCS
CQI
Active UEs
Total DL Bitrate
Max. DL Bitrate

**Comment by joshuamoorexyz** [comment]
@prateekram @bjones1 @cueltschey Now that we know the existing metrics we now need to discuss how we want to display these metrics in the GUI operating at the UE context. Can we use this issue to discuss this and when we know we can close?

First, these metrics are collected at the GnB so we will have to transfer them to our UE's host and store them before being displayed. I believe we spoke before that the sockets from client server relationship between the ue and gnb host can be incorporated in the controllers for each right?

**Comment by bjones1** [comment]
Initially, can we simply run Grafana on another machine to visualize these metrics? The UE GUI could simply launch Grafana with the correct ip address/port so this is easy. Later, we can work on fetching and displaying these metrics directly in the GUI.
