### ISSUE TITLE
Subprocess approach -- stream output

### ISSUE THREAD

**Issue by bjones1** [oran-testing/soft-t-ue#17]
For the subprocesses our code will run, I suspect that we want to capture output from these and either display it to the GUI or process it in real time (instead of waiting until the process terminates). For example:
- When we run gNB, open 5G, the UE, etc, we probably want some way to monitor and display the output of these commands as they run, perhaps even in a window in the GUI.
- When we run iperf3, we can pass the `--json` option and receive JSON output from stdout, which we need to read and gather in real time.

Unfortunately, doing this means more complexity: either we create one thread per process (at a minimum) to poll for data, or we use the async interface to some something similar, but using tasks instead of threads.

I've written code I can contribute that takes the second approach. Thoughts?

**Comment by joshuamoorexyz** [comment]
@cueltschey @bjones1 Does PR #20 take care of this issue?

**Comment by cueltschey** [comment]
in PR #20 I created a subprocess, then made a small thread that monitors the logs (no files or intermediates required). Essentially it allows us to start any process in a class, then read the real time output as a variable of that class. It also allows for efficient management of processes as objects.

Do you think this is a good method, or should we consider something else?

**Comment by joshuamoorexyz** [comment]
> in PR #20 I created a subprocess, then made a small thread that monitors the logs (no files or intermediates required). Essentially it allows us to start any process in a class, then read the real time output as a variable of that class. It also allows for efficient management of processes as objects.
> 
> Do you think this is a good method, or should we consider something else?

I saw. I believe kivy is not thread safe and async would most likely be better for collecting data in real time especially when considering multiple UEs. Would love to hear opinions on this.

**Comment by bjones1** [comment]
I did a bit of looking on kivy and threads. Per the image in the [programming guide](https://kivy.org/doc/stable/guide/events.html#attaching-callbacks), all non-GUI operations (processes appear in the diagram) can be run in a separate thread, then send back to the Kivy thread through the clock events loop. Specifically, it looks like the [mainthread decorator](https://kivy.org/doc/stable/api-kivy.clock.html#kivy.clock.mainthread) can take any function then execute it in the Kivy GUI thread. This looks like a nice, simply way to get our subprocess output to Kivy.

**Comment by cueltschey** [comment]
@bjones1 I have implemented what I read in the documentation for kivy. The logs are still collected well and it does not interfere with the GUI execution or even spawn another thread. Thanks for the great info. Since I think we have solved this problem I am closing the issue.
