### ISSUE TITLE
Detail 2 More attacks to be added to the Soft T UE

### ISSUE THREAD

**Issue by joshuamoorexyz** [oran-testing/soft-t-ue#24]
Detailed integration plan and literature review of two more attacks.

**Comment by joshuamoorexyz** [comment]
# Bandwidth Hogging Attack Using Manipulated CQI Values

## Implementation (UE Side):
  - **Override CQI:** Implement code to consistently send high CQI values.
- **Monitoring Impact:**
  - **Measure Throughput:** Track throughput and bandwidth allocated to the UE.
  - **Assess Network Impact:** Evaluate effects on other users and overall network performance.

## Mitigation Components in srsRAN gNB under test:
- **Proportional Fair Scheduling (PFS):**
  - **Balance Allocation:** Distributes resources considering channel quality and historical throughput.
  - **Limit Impact:** Adjusts allocation based on actual performance to mitigate exaggerated CQI effects.
- **CQI Reporting and Filtering:**
  - **Thresholds:** Applies thresholds to filter out unrealistic CQI values.
  - **Configuration:** Configurable to detect and handle abnormal CQI reports.
- **Quality of Service (QoS) Management:**
  - **Prioritization:** Enforces QoS policies to ensure service needs are met and mitigates bandwidth hogging.
  - **Resource Allocation:** Allocates resources based on QoS requirements.
- **Resource Allocation Limits:**
  - **Maximum Limits:** Configures resource limits to prevent excessive bandwidth use by any single UE.
  - **Rate Limiting:** Implements rate limiting for fair resource distribution.


## Metrics to Assess the Attack:
- **Bandwidth Utilization:**
  - **Throughput Measurement:** Quantify throughput allocated to the modified UE.
  - **Bandwidth Consumption:** Track percentage of total network bandwidth used by the UE.
- **Network Performance:**
  - **Impact on Other Users:** Monitor changes in service quality (throughput, latency) for other UEs.
  - **Error Rates:** Observe increases in error rates or retransmissions due to congestion.
- **Network Load:**
  - **Resource Allocation Metrics:** Measure resource usage by the attacking UE versus others.
  - **System Performance:** Assess impact on network CPU and memory usage due to increased load.

**Comment by joshuamoorexyz** [comment]
## **Attack Scenario: Signaling Storm Injection**

### **Implementation (UE Side):**

- **Custom Firmware/Software:**
  - **Gain Access:** Root or administrative access to modify UE firmware/software.
  - **Flood Signaling Messages:**
    - **Send High Volume:** Implement code to send a large number of signaling messages, such as attach requests, handover requests, or service requests, to the gNB.
    - **Simulate Overload:** Configure the UE to continuously generate and transmit signaling messages to simulate a signaling storm.

- **Custom Application:**
  - **Develop & Deploy:** Create an application on the UE that periodically sends signaling messages at high frequencies.
  - **Testing:** Ensure the application can handle different types of signaling messages and adapt to varying network conditions.

- **Monitoring Impact:**
  - **Network Response:** Observe how the gNB processes and manages the influx of signaling messages.
  - **Resource Utilization:** Assess the effect of signaling overload on the gNB’s processing capabilities and overall network performance.

### **Mitigation Components in srsRAN gNB:**

Are there Rate limiting strategies in srsRAN GnB that can be under test?

### **Metrics to Assess the Attack:**

- **Signaling Message Rate:**
  - **Rate Measurement:** Quantify the rate at which signaling messages are sent by the UE and received by the gNB.
  - **Volume Analysis:** Measure the total number of signaling messages received by the gNB over a specified period.

- **Network Performance:**
  - **Impact on Throughput:** Assess changes in network throughput and overall performance due to the influx of signaling messages.
  - **Service Disruption:** Monitor any disruptions or delays in service availability for other UEs as a result of the signaling storm.

- **Resource Utilization:**
  - **CPU and Memory Usage:** Track CPU and memory usage on the gNB to evaluate the effect of processing high volumes of signaling messages.
  - **Network Load:** Measure overall network load and resource consumption resulting from the signaling overload.

**Comment by cueltschey** [comment]
Both of these attacks are now being implemented
