### ISSUE TITLE
CQI Attack Development

### ISSUE THREAD

**Issue by Higgigamer19** [oran-testing/soft-t-ue#27]
# Bandwidth Hogging Attack Using Manipulated CQI Values

## Implementation (UE Side):
  - **Override CQI:** Implement code to consistently send high CQI values.
- **Monitoring Impact:**
  - **Measure Throughput:** Track throughput and bandwidth allocated to the UE.
  - **Assess Network Impact:** Evaluate effects on other users and overall network performance.

## Mitigation Components in srsRAN gNB under test:
- **Proportional Fair Scheduling (PFS):**
  - **Balance Allocation:** Distributes resources considering channel quality and historical throughput.
  - **Limit Impact:** Adjusts allocation based on actual performance to mitigate exaggerated CQI effects.
- **CQI Reporting and Filtering:**
  - **Thresholds:** Applies thresholds to filter out unrealistic CQI values.
  - **Configuration:** Configurable to detect and handle abnormal CQI reports.
- **Quality of Service (QoS) Management:**
  - **Prioritization:** Enforces QoS policies to ensure service needs are met and mitigates bandwidth hogging.
  - **Resource Allocation:** Allocates resources based on QoS requirements.
- **Resource Allocation Limits:**
  - **Maximum Limits:** Configures resource limits to prevent excessive bandwidth use by any single UE.
  - **Rate Limiting:** Implements rate limiting for fair resource distribution.

## Metrics to Assess the Attack:
- **Bandwidth Utilization:**
  - **Throughput Measurement:** Quantify throughput allocated to the modified UE.
  - **Bandwidth Consumption:** Track percentage of total network bandwidth used by the UE.
- **Network Performance:**
  - **Impact on Other Users:** Monitor changes in service quality (throughput, latency) for other UEs.
  - **Error Rates:** Observe increases in error rates or retransmissions due to congestion.
- **Network Load:**
  - **Resource Allocation Metrics:** Measure resource usage by the attacking UE versus others.
  - **System Performance:** Assess impact on network CPU and memory usage due to increased load.

## Notes
- **Development Branch:** cqi_attack_development

**Comment by cueltschey** [comment]
There are actually some default config options provided by srsRAN that may eliminate the need for developing this:
--phy.cqi_max -> defines maximum CQI value
--phy.cqi_fixed -> defines a fixed CQI value

I ran them both with value 100 and saw no real results
@Higgigamer19  what do you think about this?
