### ISSUE TITLE
Python GUI

### ISSUE THREAD

**Issue by joshuamoorexyz** [oran-testing/soft-t-ue#3]
Creation of a python based GUI to replace command line driven testing and key for visualization.

**Comment by bjones1** [comment]
I think we should consider using [kivy](https://kivy.org/) as a more modern GUI that's still free to use.

**Comment by bjones1** [comment]
Other Python thoughts:

1. Use [poetry](https://python-poetry.org/) for dependency management.
2. Use [pytest](https://docs.pytest.org/en/8.2.x/) for unit testing.
3. Use [black](https://black.readthedocs.io/en/stable/) for code formatting.
4. Use [flake8](https://flake8.pycqa.org/en/latest/) for linting.
5. Use [isort](https://pycqa.github.io/isort/) to sort imports nicely.
6. Use [mypy](https://mypy-lang.org/) for type checking to help spot bugs earlier in the development cycle.

I have all this set up and configured in the [old repo](https://github.com/oran-testing/srsRAN_4G/tree/ue-tester/ue-tester), so it's pretty easy to copy this across when we're ready.
