### ISSUE TITLE
Automate PCAP collection for Fuzzer test

### ISSUE THREAD

**Issue by joshuamoorexyz** [oran-testing/soft-t-ue#4]
- Investigate how this would be accomplished easily (UE does have facilities in place for packet capture but it seems the data is wrong)
- PCAPs should be automatically converted to JSON and then visualized in the GUI

**Comment by cueltschey** [comment]
We are using scapy to collect pcap data, currently working on implementing this in the GUI.

**Comment by cueltschey** [comment]
There is a bit of a change of plans regarding this. We need to collect PCAP from the srsRAN generated files, such as ue_mac_nr.pcap, then decode the PCAP into a usable format.

I am in the process of decoding these messages, since scapy has no native support for this. 

See Issue #9 for more info.
