### ISSUE TITLE
Auto call of workflow/main.yaml

### ISSUE THREAD

**Issue by aayamrajshakya** [oran-testing/soft-t-ue#57]
Hi all, it looks like the repo's workflow is set up to run on every push, which causes it to build the entire system regardless of the changes made. I recently pushed some .rst files for the RTD doc page, and the entire commit process took 40-45 minutes to complete. Is this normal?

This is me creating `.readthedocs.yaml`

![Screenshot from 2024-09-12 17-06-30](https://github.com/user-attachments/assets/d1a82296-f5ca-41b4-824a-de4a31a0bf00)
<br />
![Screenshot from 2024-09-12 17-06-44](https://github.com/user-attachments/assets/006ad3b3-a863-4ed6-af15-994de9b45350)

**Comment by cueltschey** [comment]
Yes the CI CD takes a long time. It only starts when pushing to main, which is why we avoid pushing to main too frequently.
